//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ___VARIABLE_moduleName___Presenter {
    private let wireframe: ___VARIABLE_moduleName___WireframeInterface

    init(
        wireframe: ___VARIABLE_moduleName___WireframeInterface
    ) {
        self.wireframe = wireframe
    }
}

extension ___VARIABLE_moduleName___Presenter: ___VARIABLE_moduleName___PresenterInterface {
}
