//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ___VARIABLE_moduleName___View: UIView {
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        initialize()
    }

    override init(frame: CGRect = .zero) {
        super.init(frame: frame)
        initialize()
    }

    private func initialize() {
        setupView()
        setupLayout()
    }

    private func setupView() {
    }

    private func setupLayout() {
    }
}
